services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      # Dual listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  # api:
  #   build:
  #     context: ../phase_3_predictive_analytics
  #     dockerfile: Dockerfile
  #   image: air-quality-api:latest
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     # populate if needed by future extensions
  #     KAFKA_BOOTSTRAP: kafka:29092


  api:
    build:
      context: ../phase_3_predictive_analytics
      dockerfile: Dockerfile
    image: air-quality-api:latest
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP: kafka:29092

      DATABRICKS_HOST: "https://dbc-c6e23e3f-27c7.cloud.databricks.com"
      DATABRICKS_TOKEN: ""
      MLFLOW_MODEL_URI:  "runs:/1b8830fe0f68479daddeceb22f464fa8/model" #"runs:/f84cd45793bd4cf1bfd00d6b5d933d0e/model"
      MLFLOW_TRACKING_URI: databricks

    volumes:
      - ../phase_3_predictive_analytics:/app:ro

